plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac --exclude /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/Exclude-tcga_genotypes_cptac-HRC.txt --make-bed --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP1
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP1 --update-map /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/Chromosome-tcga_genotypes_cptac-HRC.txt --update-chr --make-bed --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP2
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP2 --update-map /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/Position-tcga_genotypes_cptac-HRC.txt --make-bed --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP3
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP3 --flip /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/Strand-Flip-tcga_genotypes_cptac-HRC.txt --make-bed --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP4
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/TEMP4 --a2-allele /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/Force-Allele1-tcga_genotypes_cptac-HRC.txt --make-bed --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 1 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr1
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 1 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr1
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 2 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr2
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 2 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr2
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 3 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr3
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 3 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr3
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 4 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr4
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 4 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr4
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 5 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr5
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 5 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr5
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 6 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr6
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 6 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr6
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 7 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr7
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 7 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr7
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 8 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr8
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 8 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr8
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 9 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr9
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 9 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr9
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 10 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr10
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 10 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr10
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 11 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr11
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 11 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr11
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 12 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr12
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 12 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr12
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 13 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr13
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 13 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr13
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 14 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr14
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 14 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr14
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 15 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr15
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 15 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr15
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 16 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr16
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 16 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr16
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 17 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr17
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 17 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr17
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 18 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr18
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 18 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr18
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 19 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr19
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 19 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr19
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 20 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr20
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 20 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr20
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 21 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr21
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 21 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr21
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 22 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr22
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 22 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr22
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --make-bed --chr 23 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr23
plink --bfile /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated --real-ref-alleles --recode vcf --chr 23 --out /common/bermanblab/data/private_data/POC_ROC/POC_ROC_pQTL/temp_plink_output/plink_tcga/tcga_genotypes_cptac-updated-chr23
rm TEMP*
